name: Release to GHCR

on:
  push:
    tags: ["v*.*.*"]   # e.g., v0.1.0
  workflow_dispatch: {} # allow manual runs

concurrency:
  group: ghcr-release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set vars
        id: vars
        run: |
          VER="${GITHUB_REF_NAME#v}"  # 0.1.0
          echo "image=ghcr.io/${{ github.repository_owner }}/unified_embeddings" >> $GITHUB_OUTPUT
          echo "version=$VER" >> $GITHUB_OUTPUT

      - name: Build & Push (CPU)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.version }}
            ${{ steps.vars.outputs.image }}:latest
          labels: |
            org.opencontainers.image.title=unified_embeddings
            org.opencontainers.image.version=${{ steps.vars.outputs.version }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
          cache-from: type=registry,ref=${{ steps.vars.outputs.image }}:buildcache
          cache-to: type=registry,ref=${{ steps.vars.outputs.image }}:buildcache,mode=max
